apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
data:
  alert.rules.yaml: |
    groups:
    - name: devops-alerts
      rules:
      - alert: AppDown
        expr: up{job="kubernetes-pods"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "Application is DOWN"

      - alert: HighRequestRate
        expr: rate(hello_requests_total[1m]) > 5
        for: 30s
        labels:
          severity: warning
        annotations:
          description: "High traffic detected"

      - alert: PodRestartSpike
        expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
        for: 2m
        labels:
          severity: warning
        annotations:
          description: "Pods restarting too frequently"

