apiVersion: v1
kind: Service
metadata:
  name: devops-lab-app-svc
  namespace: devops-lab
spec:
  type: NodePort
  selector:
    app: devops-lab-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080

